[package]
name = "resize-images"
description = "Resize images in a directory"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.1"
glob = "0.3.1"
clap = { version = "4.5.6", features = ["derive"] }
